import fs from "node:fs/promises";
import path from "node:path";
import { runCommand } from "../src/utils.js";

const root = process.cwd();
const forbiddenContent = [
  /\/Users\/(?!(?:test|runner|username|example)\/)[A-Za-z0-9._-]+\//,
  /-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/,
  /\bsk-[A-Za-z0-9_-]{24,}\b/,
  /\bsk-or-v1-[A-Za-z0-9_-]{24,}\b/,
  /\bgh[opusr]_[A-Za-z0-9_]{24,}\b/,
  /generated by (?:chatgpt|codex|an? ai)/i,
  new RegExp(["target", "implementation", "agent"].join("\\s+"), "i"),
];

const tracked = (await runCommand("git", ["ls-files", "--cached", "--others", "--exclude-standard"], { cwd: root }))
  .stdout.trim().split("\n").filter(Boolean);
const violations = [];
for (const file of tracked) {
  if (/^(?:node_modules|\.council)\//.test(file) || /\.(?:vsix|pem|key|p12)$/i.test(file)) {
    violations.push(`${file}: generated, local, or credential-bearing file is tracked`);
  }
  if (file === "scripts/check-public.js") continue;
  const target = path.join(root, file);
  const contents = await fs.readFile(target, "utf8").catch(() => null);
  if (contents === null) continue;
  for (const pattern of forbiddenContent) {
    if (pattern.test(contents)) violations.push(`${file}: matched public-content guard ${pattern}`);
  }
}

const manifest = JSON.parse(await fs.readFile(path.join(root, "package.json"), "utf8"));
if (manifest.private === true) violations.push("package.json: package must be public");
if (manifest.name !== "coder-council") violations.push("package.json: public package name must be coder-council");
if (manifest.license !== "Apache-2.0") violations.push("package.json: Apache-2.0 license metadata is required");

const readme = await fs.readFile(path.join(root, "README.md"), "utf8");
if (!readme.includes("curl -fsSL https://raw.githubusercontent.com/preraktrivedi7/coder-council/main/install.sh | sh")) {
  violations.push("README.md: canonical one-line installer is missing");
}

if (violations.length) {
  process.stderr.write(`Public-release check failed:\n- ${violations.join("\n- ")}\n`);
  process.exitCode = 1;
} else {
  process.stdout.write(`Public-release check passed (${tracked.length} tracked files).\n`);
}
